name = "ogp-blog-euxn-me"
main = "src/index.tsx"
compatibility_date = "2023-05-12"

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
[[r2_buckets]]
binding = "OGP_BLOG_EUXN_ME"
bucket_name = "ogp-blog-euxn-me"
preview_bucket_name = "ogp-blog-euxn-me"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"

[placement]
mode = "smart"

